name: Publish mod

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 21
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - run: ./gradlew build modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      #- run: ./gradlew build publish
      #  env:
      #    ORG_GRADLE_PROJECT_mavenRepoUrl: ${{ secrets.MAVEN_REPO_URL }}
      #    ORG_GRADLE_PROJECT_mavenRepoUsername: ${{ secrets.MAVEN_REPO_USERNAME }}
      #    ORG_GRADLE_PROJECT_mavenRepoPassword: ${{ secrets.MAVEN_REPO_PASSWORD }}
      #    ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_SIGNING_KEY }}
      #    ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
